name: AI Job Hunter

on:
  schedule:
    - cron: "0 * * * *"  # Every hour (UTC)
  workflow_dispatch:

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run AI Agent with logging (keep last 10 logs)
        run: |
          mkdir -p logs
          log_file="logs/run_$(date +"%Y-%m-%d_%H-%M-%S").log"
          python main.py > "$log_file" 2>&1
          
          # Keep only last 10 logs
          ls -t logs/*.log | tail -n +11 | xargs -r rm --

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: ai-agent-logs
          path: logs/
